### ISSUE TITLE
Setup core concepts around attribute kinds CRUD

### ISSUE THREAD

**Issue by stsh89** [stsh89/metropolis#4]
## Features

* [x] List
* [x] Get
* [x] Create
* [x] Update
* [x] Delete

## Tasks

* [x] Implement model attribute kinds CRUD
* [x] Add datastore proto definitions
* [x] Add API proto definitions
